# Настройки выделения памяти для Gradle по умолчанию
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Включение AndroidX
android.useAndroidX=true

# Включение параллельной сборки модулей для ускорения компиляции
org.gradle.parallel=true

# ИСПРАВЛЕНО: Отключает ошибку нестыковки версий Java при компиляции Kotlin-кода
kotlin.jvm.target.validation.mode=warning

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
